Public Module Hues
    Public Const Black = "black"
    Public Const Blue = "blue"
    Public Const Green = "green"
    Public Const Cyan = "cyan"
    Public Const Red = "red"
    Public Const Magenta = "magenta"
    Public Const Brown = "brown"
    Public Const Gray = "gray"
    Public Const DarkGray = "darkgray"
    Public Const LightBlue = "lightblue"
    Public Const LightGreen = "lightgreen"
    Public Const LightCyan = "lightcyan"
    Public Const LightRed = "lightred"
    Public Const LightMagenta = "lightmagenta"
    Public Const Yellow = "yellow"
    Public Const White = "white"
End Module
