Public Enum GameState
    Title
    MainMenu
    ConfirmQuit
    EditMenu
    FontsMenu
    NewFontSize
    PickFont
    NewFontName
    EditFont
    EditGlyph
    SaveAs
    LoadFrom
    TerrainsMenu
    NewTerrainName
    EditTerrain
    PickTerrainFont
    PickTerrainGlyph
    PickTerrain
    MapsMenu
    NewMapName
    PickMap
    NewMapSize
    EditMap
    Settings
    PickMapTerrain
    PlaceMapTerrain
    PickDefaultMapTerrain
    RenameMap
    PickRenameFont
    PickCloneFont
    PickDeleteFont
    RenameFont
    CloneFont
    Messages
    ConfirmDeleteFont
    RenameTerrain
    CloneTerrain
    ConfirmDeleteTerrain
    CloneMap
    ConfirmDeleteMap
    ItemsMenu
    NewItemName
    PickItem
    EditItem
    PickItemGlyph
    PickItemFont
    RenameItem
    CloneItem
    ConfirmDeleteItem
    PickMapItem
    PlaceMapItem
    RemoveMapItem
    CreaturesMenu
    NewCreatureName
    PickCreature
    EditCreature
    PickCreatureGlyph
    PickCreatureFont
    RenameCreature
    CloneCreature
    ConfirmDeleteCreature
    PickExportFont
    ExportFontAs
    PickMapCreature
    PlaceMapCreature
    RemoveMapCreature
    AvatarMenu
    PickAvatarMap
    PickAvatarCreatureInstance
    Navigate
    GameMenu
End Enum
