Public Enum GameState
    Title
    MainMenu
    ConfirmQuit
    EditMenu
    FontsMenu
    NewFontSize
    PickFont
    NewFontName
    EditFont
    EditGlyph
    SaveAs
    LoadFrom
    TerrainsMenu
    NewTerrainName
    EditTerrain
    PickTerrainFont
    PickTerrainGlyph
    PickTerrain
    MapsMenu
    NewMapName
    PickMap
    NewMapSize
    EditMap
    Settings
    PickMapTerrain
    PlaceMapTerrain
    PickDefaultMapTerrain
    RenameMap
    PickRenameFont
    PickCloneFont
    PickDeleteFont
    RenameFont
    CloneFont
End Enum
